apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
  namespace: todo-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-pod
        image: latesteef7390b5cc964e0f3a36dbca73273d502c2a160
        ports:
        - containerPort: 8000   

---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app-ns
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30009
