version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  push-github:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: sed -i "s+latest.*+latest$CIRCLE_SHA1+" deployment.yaml
          name: Update manifest
      - run:
          command: |
            git config user.email admin@example.com
            git config user.name admin
            git add deployment.yaml
            git commit -m "Updated image $CIRCLE_SHA1 [skip ci]" 
            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/Project-1.git
          name: Push to github
  deploy-prod:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          todo-cluster
        type: string
    steps:
      - checkout
      - run:
         command: |
           sed -i "s+latest+$ECR_URI+" deployment.yaml
           sed -i "s/todo-app-ns/todo-app-prod-ns/g" deployment.yaml
           sed -i "s/30009/30007/g" deployment.yaml
         name: updated prod manifest
      - run:
          command: |
            /usr/bin/kubectl apply -f deployment.yaml
          name: Deploy on prod env        
  deploy-dev:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          todo-cluster
        type: string
    steps:
      - checkout
      - run:
         command: sed -i "s+latest.*+$ECR_URI$CIRCLE_SHA1+" deployment.yaml
         name: updated dev manifest
      - run:
          command: |
            /usr/local/bin/kubectl apply -f deployment.yaml
          name: Deploy on dev env
workflows:
  build-push-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          path: .
          create-repo: true
          repo: node-js
          tag: todo_app$CIRCLE_SHA1
          skip-when-tags-exist: true
          filters:
            branches:
              only: dev
      - deploy-dev:
          cluster-name: todo-cluster
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: dev  
      - push-github:
          requires:
            - deploy-dev
          filters:
            branches:
              only: dev  
      - deploy-prod:
          cluster-name: todo-cluster
          filters:
            branches:
              only: prod
